### ISSUE TITLE
Release 0.1.5?

### ISSUE THREAD

**Issue by anuraaga** [openzipkin/zipkin-go#104]
I was optimistically hoping #96 would get in before another tagged release but unfortunately 0.1.4 doesn't have it. #96 made this backwards incompatible change (removal of `WithRPCHandler` since we found it to be overkill). 

https://github.com/openzipkin/zipkin-go/pull/96/files#diff-e9d00f5e4c269bd123203c5aff2f336eL34

Does it make sense to release 0.1.5 quickly and consider 0.1.4 a skipped release? Sorry for the trouble.

/cc @jcchavezs @basvanbeek

**Comment by basvanbeek** [comment]
no you're right.... 0.1.4 should not have been released yet... I've fixed by doing a 0.1.5.
