### ISSUE TITLE
Specifying a http proxy

### ISSUE THREAD

**Issue by Bitneko** [openzipkin/zipkin-go#106]
How do I specify a http proxy in the client with zipkin-go’s client? Using the http package, I would specify it in the following way.

```
client = http.Client{
    Transport: &http.Transport{
        Proxy: http.ProxyURL(proxyURL),
    },
}
```

**Comment by jcchavezs** [comment]
You can use this options to pass the client: https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/client.go#L29 or pass `Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)},` to https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/transport.go#L24.

In any case, please don't ask usage questions here. Head to https://gitter.im/openzipkin/zipkin for further questions.
