### ISSUE TITLE
Adds support for `RemoteEndpoint` in transport/client

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#108]
Often it is useful to add remoteEndpoint to the client spans. Specifically http requests.

Currently nor the client or the transport support this functionality. The most logical options that comes to my mind is that we add an option for both.

Ping @basvanbeek @adriancole

**Comment by basvanbeek** [comment]
Yes this would be a nice to have.

**Comment by basvanbeek** [comment]
done and released
