### ISSUE TITLE
Starting spans with a given trace ID

### ISSUE THREAD

**Issue by hsiddulugari** [openzipkin/zipkin-go#111]
Here's a use case:
- A job is distributed across multiple services
- Most of the services are implemented in Java so they use Brave Zipkin library
- There's one service implemented in Golang which participates in doing some tasks for the overall job and it polls for work (instead of being asked to work)
- If the service in Golang was receiving "requests" to do the work, we could use RPC header to inject span context that can be extracted but that's not the case here
- If the service in Golang can receive trace ID (or span context) in request payload and use that to start span in order to continue the timeline of trace started somewhere else, that'll collapse all work under the same trace ID and easy to visualize in UI

The Tracing.Builder API in Brave supports this feature so I would love to see a similar feature in Go.

@adriancole

**Comment by devinsba** [comment]
The existing `Extract` method on the `Tracer` should cover this case, you would just need to provide an implementation of: `propagation.Extractor` that handles the particulars of your payload

**Comment by jcchavezs** [comment]
Exactly. You just need to write your own extractor.

Den ons. 13. feb. 2019, 22:02 skrev Brian Devins-Suresh <
notifications@github.com:

**Comment by hsiddulugari** [comment]
I see.  Let me give that a try.  Thanks for a quick response @devinsba and @jcchavezs

**Comment by basvanbeek** [comment]
For completeness sake if writing a propagation.Extractor is not fitting (e.g. you don't have a concept of a headers object being able to provide the span identifiers) you can even create a SpanContext manually and use as parent to a new span like this:

```go
// manually create SpanContext
sc := model.SpanContext{
  TraceID: myTraceID,
  ID:      mySpanID,
  ...
}
// create our local root span
span := tracer.StartSpan(
    "mySpan",
    zipkin.Kind(model.Server),
    zipkin.Parent(sc),
   ...
}
```

**Comment by hsiddulugari** [comment]
Sweet!
@basvanbeek, That is exactly what I had done in my project before asking the question here :) :
```
spanContext := model.SpanContext{TraceID: traceId, ID: 1}
span := tracer.GlobalTracer().StartSpan(name, zipkin.Parent(spanContext))
```

I was thinking it is a hack.  Glad to know it is not.

**Comment by jcchavezs** [comment]
Piece of advice: I would write it as a middleware, that way you can plug
and unplug it transparently.

Den tor. 14. feb. 2019, 20:23 skrev hsiddulugari <notifications@github.com:
