### ISSUE TITLE
Add async support for zipkin-Go while propagating

### ISSUE THREAD

**Issue by MrLina** [openzipkin/zipkin-go#116]
We use a goroutine to accept the request，and creating a span 。but we use a annother goroutine to handle the response。so if we need to finsh the span ，we need to save the span while accepted the request ，but the performance of this way is unacceptable。 Like the case of async ，Hope the feature can be support in zipkin-Go。

**Comment by basvanbeek** [comment]
I'm not sure I understand the problem. How is performance unacceptable for starting a Span somewhere, then propagating that same same span over to another goroutine where the response is handled and finish it there? Can you show in code what you are trying to achieve?

**Comment by MrLina** [comment]
create a span in a goroutine，how can i finsh the span in another goroutine ？Is there has someway to support the async invoke case？

**Comment by basvanbeek** [comment]
Please show source code of what you want to instrument. There is nothing in Zipkin Go that does not allow you to manage a span in different go routines. It completely depends on what you are trying to do what the solution is. Are you using some framework for the request and response go routines. Is there a mechanism to propagate the span from request handler to response handler. Without more details we can't help you.

**Comment by basvanbeek** [comment]
@MrLina can you help us move the solution to your concern forward otherwise I will be closing the issue as it is very well possible to do async as well as multi green thread handling of spans.

If you can show me code where we can't handle this we can make it into an actionable item.

**Comment by MrLina** [comment]
There is no problem Now,Thanks.

**Comment by MrLina** [comment]
There is no problem Now,Thanks.
