### ISSUE TITLE
Latest tagged version still requires a bad grpc module version

### ISSUE THREAD

**Issue by dmitshur** [openzipkin/zipkin-go#117]
This is a continuation of issue #114.

It has been resolved via PR #115, which has been merged. However, a new tag hasn't been created yet, which means v0.1.5 is still the latest version of zipkin-go, and now that `golang.org/x/lint` has a [go.mod file again](https://github.com/golang/lint/commit/d0100b6bd8b389f0385611eb39152c4d7c3a7905), the latest version of zipkin-go is running into the same issue as described in #114.

It can be reproduced with Go 1.12 as follows:

```
$ cd $(mktemp -d)
$ go mod init m
go: creating new go.mod: module m
$ go get -u github.com/openzipkin/zipkin-go
go: finding github.com/golang/lint latest
go: finding github.com/eapache/go-xerial-snappy latest
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: finding honnef.co/go/tools latest
go: finding google.golang.org/genproto latest
go: finding github.com/golang/glog latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/lint latest
go get: error loading module requirements
$ echo $?
1
```

Please consider making a new tag that includes the fix from PR #115 in order to fix the latest version of zipkin-go. Thanks!

**Comment by jcchavezs** [comment]
I will create such tag today.

Den tor. 14. mar. 2019, 07:45 skrev Chris Broadfoot <
notifications@github.com>:

**Comment by jcchavezs** [comment]
Done https://github.com/openzipkin/zipkin-go/releases/tag/v0.1.6

**Comment by dmitshur** [comment]
Thank you for doing that!

Unfortunately, while making the new tag helped, it wasn't sufficient to resolve the issue. The bad grpc v1.16.0 still ends up being in the build list (but now for other reasons):

```
$ cd $(mktemp -d)
$ go mod init m
go: creating new go.mod: module m
$ go get -u github.com/openzipkin/zipkin-go
go: finding github.com/openzipkin/zipkin-go v0.1.6
...
go: finding google.golang.org/grpc v1.16.0
...
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
...
go get: error loading module requirements

I'm finding the following reasons for grpc v1.16.0 showing up:

1. Latest pseudo-version of `golang.org/x/build` module lists it as an indirect require:

 
 https://github.com/golang/build/blob/2deca50d970debd63fb366d0b33900f02482af05/go.mod#L34

  This is tracked by https://github.com/golang/go/issues/30833 and will be quick to resolve.

2. Latest version of module `github.com/googleapis/gax-go/v2` is version `v2.0.3`, and it requires bad grpc version directly.

   This is tracked by https://github.com/googleapis/gax-go/issues/82. /cc @broady

    Will need to see if the latest version of any other module requires `github.com/googleapis/gax-go/v2@v2.0.3; if so, that'll need to be fixed too.

3. Latest pseudo-version of module `google.golang.org/genproto`, including pseudo-verisions `v0.0.0-20181202183823-bd91e49a0898` and `v0.0.0-20181219182458-5a97ab628bfb`, are affected.

    This is tracked by https://github.com/google/go-genproto/issues/151 and needs more investigation.

Those 3 are the only reasons I'm spotting at this time. Will update this as progress is made on resolving them.

**Comment by jadekler** [comment]
cc @dfawley

**Comment by dmitshur** [comment]
There's been progress made. Right now, I think one of the next blocking pieces to resolve is https://github.com/googleapis/google-api-go-client/issues/342 and https://github.com/census-instrumentation/opencensus-go/issues/1064#issuecomment-473136999.

Once those are resolved, the latest version of `cloud.google.com/go` may be resolved, which is required indirectly by zipkin-go. I'll post update as progress happens.

**Comment by jadekler** [comment]
We've resolved https://github.com/googleapis/google-api-go-client/issues/342 and https://github.com/census-instrumentation/opencensus-go/issues/1064#issuecomment-473136999.

**Comment by dmitshur** [comment]
All of the reasons this issue had been triggering have been resolved by now, and so this issue is fixed. It's possible to use `go get -u` with the latest version of this module successfully now. Thanks everyone!
