### ISSUE TITLE
Allow access to response in the errorHandler

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#126]
Currently error handler supports a transport error and a status code:

`type ErrHandler func(sp zipkin.Span, err error, statusCode int)`

There are well known cases where the api returns meaningful errors in the response payload and those errors would be much better in traces e.g.:

`{"error": "INVALID_TYPE"}`

I think the error handler is the piece where we can pass the resp.Body, the only challenge here is that we might need to mutate it after the read (to be able to read it again). This sounds to me safe as long **as we only do that on http error code** (which [we do already](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/transport.go#L158)) as when in error status code, the payload of the response is usually the error description (and it is mostly short payload). A proposed interface would be:

`type ErrHandler func(sp zipkin.Span, err error, statusCode int, resBody io.ReadCloser)`

A related implementation can be found in https://github.com/elastic/go-elasticsearch/blob/master/estransport/estransport.go#L115

Ping @basvanbeek @adriancole @stakhiv

**Comment by basvanbeek** [comment]
I'm OK with an implementation as long as we can explicitly enable/disable this behavior.

**Comment by jcchavezs** [comment]
Yeah, the so the default errHandler will do nothing with the response.Body.

My question was more whether this is the right place.

fre. 17. mai 2019, 15:46 skrev Bas van Beek <notifications@github.com>:

**Comment by adriancole** [comment]
FWIW in brave you have access to the whole request. we just dont abstract
things like body. by not encouraging mutations of body I think sounds good

**Comment by jcchavezs** [comment]
Request or response? Could you (when have time) point a link?

fre. 17. mai 2019, 16:41 skrev Adrian Cole <notifications@github.com>:
