### ISSUE TITLE
RequestSampler for client

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#128]
[Brave http client instrumentation allow users to inject a sampler](https://github.com/apache/incubator-zipkin-brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpClientHandler.java#L58) at client level and it would be great to include something similar here. Currently we only have `RequestSampler` for [server middleware](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/server.go#L34) but the same interface could perfectly work for the client middleware.

The use case is a request that is not sampled by default (maybe internal endpoint) but you might want to trace a specific request to other service. My use case is that I do sampling 33% but I want to trace 100% requests to a payment endpoint and right now I don't have means to make the payment endpoint to be traced 100% as my sampling policy is global (and it is a monolith with LOTS of endpoints).

Ping @adriancole @basvanbeek

**Comment by basvanbeek** [comment]
Makes sense to enable the feature.

**Comment by basvanbeek** [comment]
done in #133.
