### ISSUE TITLE
Server side request sampler should take precedence if available

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#129]
Currently `RequestSampler` is [only being invoked in the lack of sampling decision](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/server.go#L103), tho I see a lot of potential on reverting sampling decision for interesting operations that are only in the knowledge of the endpoint itself and not in the upstream knowledge.

Does it make sense for the request sampler to act even when sampling decision is to not sample from upstream?

Ping @basvanbeek @adriancole

**Comment by adriancole** [comment]
in brave, we sample the other way. request sampler takes precedence.

Note: there's some design debt in general with cascading decisions and which credits apply. ex is 50/s at path /foo and tracer is 100/s, do they combine? Currently, at least in brave, they don't.

**Comment by jcchavezs** [comment]
I would prefer that also here.

Regarding your concern of budget overflow, I think the if someone wants to
do that balancing the only way is that both `Sampler` and `RequestSampler`
share a state (maybe being the same object implementing two interfaces) but
that looks to me more an implementation detail rather than a design
decision.

What do you think about the requestSampler having precedence? @basvanbeek?

ons. 12. jun. 2019, 12:16 skrev Adrian Cole <notifications@github.com>:

**Comment by basvanbeek** [comment]
Let's have requestSampler take precedence if available.

**Comment by basvanbeek** [comment]
The one main question still open is if we should alter the function type to be the same and mean the same as the client side sampler: 

```go
func(r *http.Request) *bool
```

I prefer yes even though breaking change

**Comment by jcchavezs** [comment]
I think here it applies the same reasoning. Since we are still under 0.x I
would introduce the breaking change but maybe it is worth to ask
@ricardogama whether he uses the feature or not. WDYT?

ons. 10. jul. 2019, 00:06 skrev Bas van Beek <notifications@github.com>:

**Comment by adriancole** [comment]
I think the function type parity makes sense.
