### ISSUE TITLE
Add example code

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#136]
Currently we don't have any example in this library that we for example have in https://github.com/openzipkin-contrib/zipkin-go-opentracing/tree/master/examples (which was a first implementation of zipkin). We could either port those examples in here or create new ones.

Ping @basvanbeek @adriancole

**Comment by jcchavezs** [comment]
Sorry I did not see the existing example.

**Comment by adriancole** [comment]
noting just cause.. I still would prefer a zipkin-go-example repo that is independent. it makes things more discoverable especially as only a few of our libraries doesn't have something like this. Also, it helps separate out a usability statement from those actively working on the library and customizing it. anyway this opinion of mine is pretty well known, so just mentioning it in case relevant.
