### ISSUE TITLE
Adding 'FinishedWithDuration' to Span interface

### ISSUE THREAD

**Issue by NETkiddy** [openzipkin/zipkin-go#137]
I've noticed that **_func (s *spanImpl) FinishedWithDuration(d time.Duration)_** was added to support duration when finish. 

How about adding this api into the Span interface.

It's helpful under the case which who want to report the span with some rate control.

**Comment by jcchavezs** [comment]
It makes totally sense, the reason why I did not expose when added it was because did not want to increase the surface of the API with a real use case, tho @basvanbeek already suggested this could become a first class method in the API:

>I actually like the idea of precomputed duration. We could also make that a first class citizen to the Zipkin Go API and then for the OpenTracing wrapper basically calculate duration from Finish-Start.

https://github.com/openzipkin/zipkin-go/pull/113#issuecomment-491000650

What about coming with a PR for this @NETkiddy ?

**Comment by NETkiddy** [comment]
check it here #138

**Comment by adriancole** [comment]
there are some design notes here. just food for thought. OT at least in java requires the timestamp parameter on finish.. https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java#L211

It would be nice to understand rationale more completely before adding apis also.

> It's helpful under the case which who want to report the span with some rate control.

can you elaborate on this? how does an additional method provide for that? If doing rate-limited reporting, it seems better to use the backend of the api (ex the part that sends the structs) as opposed to the front-end of the api (the part recording measurements)

**Comment by NETkiddy** [comment]
> can you elaborate on this? how does an additional method provide for that? 

Right now for me, I store the span meta data in msgq on sending or recving req. And then maybe every some seconds I may re-instrument the span data and upload it. The meta data Timestamp can be set by a SpanOption StartTime(time.Time), while the Duration do not. With FinishedWithDuration(d time.Duration) supported it can be done. 

>  If doing rate-limited reporting, it seems better to use the backend of the api (ex the part that sends the structs) 

Seems that the Duration can be and only can be calculated once Finish() is called, so sending the structs properly will lead to a incorrect Duration value.

**Comment by adriancole** [comment]
I suppose what I'm trying to understand is if the instrumentaton is
totally out of band, could you not use the api directly, like this
https://github.com/openzipkin/zipkin-api-example/blob/master/go/post_sample_trace.go

**Comment by NETkiddy** [comment]
the reason why using the api directly is that I have to use the kafka reporter to upload spans (server side‘s restriction). 

If the API of Finish() can support duration (or timestamp as you pointed out in java, or maybe expose FinishedWithDuration) that'll be great.

**Comment by basvanbeek** [comment]
I've merged the PR adding the FinishedWithDuration to the interface. I think it makes sense as supporting a setable Finish timestamp can lead to unexpected results (monotonicity not guaranteed) and FinishedWithDuration was already implemented in the Span implementation (for usage with the OT bridge).

We couldn't really hide the function anyway as this would have worked too (just burning unnecessary extra CPU cycles)

```go
type DurationFinisher interface {
    FinishedWithDuration(time.Duration)
}

if sd, ok := span.(DurationFinisher); ok {
    sd.FinishedWithDuration(duration)
}
```
