### ISSUE TITLE
Change parameter type of http.Logger() to interface

### ISSUE THREAD

**Issue by fho** [openzipkin/zipkin-go#144]
The http.Logger() interface expects a `log.Logger` type as parameter.

Instead of expecting `log.Logger`, define a simple logger interface with the `Printf()` method and change the parameter to that interface.

That will allow to use other loggers then `log.Logger` of the stdlib as reporter logger.

**Comment by jcchavezs** [comment]
We did something similar for the HTTP client, could you at least explain more the use case and why it can't be solved with the current logger (maybe convenience or actual technical challenge).

**Comment by basvanbeek** [comment]
closing as related to / subset of #37

**Comment by fho** [comment]
@jcchavezs We use in our applications a different logger then the one from the stdlib.
Currently it is not possible to log messages from zipkin-go to our logger. It's only possible to log messages to the stdlib logger.

I want to use our logger because it e.g. prints messages in  JSON-format to stdout.

**Comment by basvanbeek** [comment]
@fho the use case you describe fits issue #37 which I'll pick up after my holiday. I am not guaranteeing you can directly use your `Printf()` method but a simple bridge function in between will be possible.
