### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-go#15]
@abesto what's in your opinion the best tool considering various things you may have run into. Seems codecov vs coveralls? or maybe something else

cc @openzipkin/devops-tooling

**Comment by abesto** [comment]
I've used coveralls in the past, been happy with it – https://github.com/abesto/easyssh (https://coveralls.io/github/abesto/easyssh) is a project in Go using Coveralls and being happy. https://github.com/lemurheavy/coveralls-public/issues/329 may be a potential deal-breaker for you, or irrelevant.

Don't have first-hand experience with codecov, looks pretty mature at a glance.

I don't know of any others that do hosted free coverage history.

**Comment by basvanbeek** [comment]
I've added coveralls... i don't care too much about not being able to customize the badge color wrt thresholds
