### ISSUE TITLE
Configuring client for better load balancing

### ISSUE THREAD

**Issue by maxbischoff** [openzipkin/zipkin-go#152]
I am using the zipkin-go client in a kubernetes environment, where few instances using the client should load balance to many zipkin collectors (The concrete context is in https://github.com/istio/istio/issues/17754).
In my environment the clients start reporting to a single collector endpoint and re-use their connection for very long, causing all traffic of a client going to a single collector instance. Furthermore, as load balancing is random, this also often causes traffic from two clients going to the same collector instance.
Is there documentation on configuring the http reporter in a sensible way, to achieve an even load balancing from a single client to multiple backendso r can you provide me advice on how to achieve this?

**Comment by basvanbeek** [comment]
You can tweak the http.Client used by Zipkin by providing it a custom initialized one.
See:
https://github.com/openzipkin/zipkin-go/blob/master/reporter/http/http.go#L202:205
