### ISSUE TITLE
panic when openzipkin/zipkin-go/model.SpanModel.MarshalJSON 

### ISSUE THREAD

**Issue by renwotao** [openzipkin/zipkin-go#157]
hi，
      when I use openzipkin and kafka reporter , I found corruption in k8s env.
![1573465170282](https://user-images.githubusercontent.com/8586620/68577035-3ba76900-04aa-11ea-89aa-b69b4ae63de9.jpg)
       Thanks for help.

**Comment by renwotao** [comment]
2nd pictures about issue
![image](https://user-images.githubusercontent.com/8586620/68577331-d6a04300-04aa-11ea-8a92-3eb2808480dd.png)

**Comment by renwotao** [comment]
openzipkin version:
`github.com/openzipkin/zipkin-go v0.2.0`

grpc verison:
`google.golang.org/grpc v1.23.0`

**Comment by jcchavezs** [comment]
I checked this issue. The issue seems to be that a Tag is added during the span being reported. This does not seem to be very likely but in case this is possible, are you doing any tagging right after the reporting?

Finally, it could be interesting if we could give a shot to https://golang.org/pkg/sync/#Map for `SpanModel` but as far as I saw, we might need to do quite big test changes.

Any idea @basvanbeek ?

**Comment by renwotao** [comment]
> I checked this issue. The issue seems to be that a Tag is added during the span being reported (actually while marshalling for reporting). This does not seem to be very likely but in case this is possible, are you doing any tagging right after the reporting?
> 
> As for the error, apparently, [syncMap](https://golang.org/pkg/sync/#Map) was designed for such issues, but as far as I saw, we might need to do quite big test changes.
> 
> If this is really the issue, there are other easier alternatives, one could be to copy the tag values on [Finish](https://github.com/openzipkin/zipkin-go/blob/master/span_implementation.go#L79) and before reporting or either reset the tags map after finish but I would really like to make sure this is the issue before we jump into conclusions.
> 
> Any idea @basvanbeek?

thx for your reply，I find the reason，span call tag when grpc close in different go routines。
