### ISSUE TITLE
Don't include the http.status_code when 2xx in server

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#162]
According to https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpResponseParser.java#L67, by default `http.status_code` tag should only be present if the tag is not `2xx`. It makes sense to replicate this condition here in [server instrumentation](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/server.go#L151) given that [client does it already](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/client.go#L130).

**Comment by dengliming** [comment]
+1

**Comment by jcchavezs** [comment]
Thanks @dengliming
