### ISSUE TITLE
Update proto generated files to `github.com/golang/protobuf v1.4.2` or newer

### ISSUE THREAD

**Issue by bogdandrutu** [openzipkin/zipkin-go#164]
https://github.com/openzipkin/zipkin-go/tree/master/proto/v2 it is generated with a very old protobuf library (deprecated now). Would be good to update these files to the latest protobuf library.

**Comment by adriancole** [comment]
just to spread things to folks who usually work in this area and might be able to knock out quicker.. cc @jcchavezs @basvanbeek any impact to do this (help wanted if you can)

**Comment by bogdandrutu** [comment]
Thank you
