### ISSUE TITLE
Should we still support 1.9?

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#169]
Currently travis is failling for Go 1.9 because of a GRPC incompatibility.

[grpc-go deprecated support for Go 1.9](https://github.com/grpc/grpc-go/commit/bc714cd8aeaa4f1a59e055b5a6411a04b17fd319) and since 1.9 does not support go mod, latest version is pulled and hence the problem.

We could either do some hacks to pin the grpc-go version or just deprecate 1.9 support.

**Comment by basvanbeek** [comment]
Let's deprecate

**Comment by jcchavezs** [comment]
Cool I will do that today.

tir. 11. aug. 2020, 10:36 skrev Bas van Beek <notifications@github.com>:

**Comment by basvanbeek** [comment]
closed by #172
