### ISSUE TITLE
Function to get TraceID

### ISSUE THREAD

**Issue by androna-xm** [openzipkin/zipkin-go#195]
Is there a function to get the TraceID of a trace created?

**Comment by jcchavezs** [comment]
Only on reporting. What are you trying to achieve?

**Comment by androna-xm** [comment]
I would like to get the TraceID to add it as an exemplar to a metric. So i guess i have to use an  instrumentation tool ( Opencencus or OpenTelemetry ) to get the TraceID ?

**Comment by basvanbeek** [comment]
You do have access to TraceID from span context:

```go
// get as hex string (the typical propagation format)
span.Context().ID.String()
```

**Comment by jcchavezs** [comment]
@basvanbeek is totally right, I misunderstood the question.

As he pointed out you can access to it through the context so you can use that and put in the metric.

**Comment by androna-xm** [comment]
That's great! Thank you!
