### ISSUE TITLE
Convert over to "official" rabbitmq library

### ISSUE THREAD

**Issue by SteelPhase** [openzipkin/zipkin-go#198]
the RabbitMQ team has pulled in https://github.com/streadway/amqp into https://github.com/rabbitmq/amqp091-go

You can see the conversation [here](https://github.com/streadway/amqp/issues/497#issuecomment-791068860)

**Comment by jcchavezs** [comment]
Thanks for pointing that out, are you up to do such change?

José Carlos Chávez


tor. 19. aug. 2021 kl. 23:40 skrev SteelPhase ***@***.***>:
