### ISSUE TITLE
Export  noopSpan type

### ISSUE THREAD

**Issue by honghzzhang** [openzipkin/zipkin-go#48]
Can we export noopSpan type or let me know how else I could check whether a given span is a noopSpan?

**Comment by jcchavezs** [comment]
I guess what you need is that somehow determine whether a span context is noop or not. I would instead add the `Span::IsNoop` method instead like in brave: https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java

Thoughts @basvanbeek ?

**Comment by basvanbeek** [comment]
Is this needed because having a sampled span implies needing to do additional expensive computation?

I kind of want to make sure we don't add things as long as they are not really needed. I would like to hear about a proper use case for this.

**Comment by honghzzhang** [comment]
I am trying to convert a Java project which uses zipkin tracing to Go. In the java project, it calls the brave API Span.isNoop() to determine whether to propagate the span and I was trying to find the equivalent API from the zipkin-go project.

**Comment by jcchavezs** [comment]
I'd recommend that you don't check the noop and propagate the context (with `X-B3-SAMPLED=0`) as the recipient will create noop spans instead but I am curious whether there is another use case behind that. @adriancole can you think on a use case for this?

**Comment by honghzzhang** [comment]
If I propagate the context (with X-B3-SAMPLED=0), will the recipient always create noop span or it knows to only create noop spans when applicable?

**Comment by basvanbeek** [comment]
Ok, so one of the most important aspects to propagation is to always propagate! How would a downstream service otherwise know that the trace was not sampled? It could start a new trace because without propagation it thinks it is the trace root.

**Comment by jcchavezs** [comment]
True but IMO if context contains `sampled=false` we should create noop spans. I raised an issue to discuss this: https://github.com/openzipkin/zipkin-go/issues/49

**Comment by adriancole** [comment]
I would treat noop different than sampled knowing what I know now.

Here is why.. in firehose mode we will collect regardless of sample flag,
but look at the context to see if we should report to zipkin or not. It is
only because we have isNoop that we can do this without breaking people..

**Comment by jcchavezs** [comment]
I see. If the reason why is firehose them we probably need to do the same in other libraries, otherwise if one of our libraries creates a noop object we will miss that piece. Is this something already happening in brave?

**Comment by adriancole** [comment]
>
> I see. If the reason why is firehose them we probably need to do the same
> in other libraries, otherwise if one of our libraries creates a noop object
> we will miss that piece.
>
In census I think this is called "always record events" or similar. In
brave, the isNoop guard is regularly used to prevent parsing expensive
things, so yeah if you want to capture all data you need a mechanism to
opt-out when it is pointless (ex when unsampled and there is no other sort
of listener, it is pointless to spend time creating data only to be thrown
on the floor)

> Is this something already happening in brave?
>
it isn't done yet. first to do this way py_zipkin

**Comment by basvanbeek** [comment]
There is merit in knowing when a span is recording items or if not (ex. noopSpan). As said above this helps with avoiding expensive computations and unnecessary burning of cpu cycles. 

I do want to have this be part of the bigger scope of work on firehose mode. So closing here. 

Firehose mode is discussed in #58
