### ISSUE TITLE
Provide instrumentation for standard libraries

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#56]
In order to embrace the usage of zipkin-go we should provide some standard library instrumented. `http.Client`, `http.Handler` and `sqlx.DB` would be the first candidates.

Creating a repo in `openzipkin` or `openzipkin-contrib` under the name `zipkin-go-instrumentation` or `go-instrumentation` would be enough (similar to https://github.com/opentracing-contrib/go-stdlib).

I [build myself one library](https://github.com/jcchavezs/zipkin-instrumentation-sqlx) for `sqlx` that I could happily move there.

Ping @basvanbeek  @adriancole

**Comment by adriancole** [comment]
up to you all. I think OT tends to create more repositories.. one benefit of that is looking more impressive. I personally find it easier to assess change if certain highly reused instrumentation are in the same repo, similar to how things are in zipkin-ruby, brave, zipkin4net and zipkin-js.

**Comment by adriancole** [comment]
feel free to create such a repo

**Comment by jcchavezs** [comment]
I just updated the issue. It does not have to be under `openzipkin-contrib` it can perfectly be in `openzipkin`.

**Comment by basvanbeek** [comment]
So after some time to think about it I would like to do the following:

have middleware be part of the project if:
- highly used
- dependencies are light or simply standard library
- opaque to consumer (no struct wrapping but interface with embedded traced component)

This means http middleware is in. sqlx is out. however database/sql driver wrappers can be in.

I'm conflicted on gRPC as it does not meet the above criteria wrt dependencies. For now I think I'll keep it out.

Currently we have instrumentation for HTTP be part of the library. We'll open other issues for specific middleware requests.

**Comment by jcchavezs** [comment]
@basvanbeek shall we remove [this](https://github.com/openzipkin/zipkin-go/blob/master/middleware/http/client.go) `Client` struct then? I would just keep the `RountTripper` and add some documentation on how to use it.

**Comment by basvanbeek** [comment]
Even though that one violates the 3rd requirement I'm not sure I want to lose it as it has benefits to keep a middleware that uses application spans.

Improved / additional documentation is fine for both... feel free to draft...

**Comment by jcchavezs** [comment]
I would honestly move to `contrib`. Although it is great I don't see myself
using the zipkin.Client type in my infrastructure as it is an
implementation detail that I would avoid by using an interface on front.--

*José Carlos*
