### ISSUE TITLE
Should we record `http.request.size` when in `GET` or when it is 0?

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#80]
Lately I saw many traces including the `http.request.size=0` in some server spans and I am thinking this is just adding buzz when it comes to `GET` requests or when the value is `zero`. What do you think?

cc @adriancole @basvanbeek

**Comment by basvanbeek** [comment]
I think we should omit as it's just added noise this way

**Comment by jcchavezs** [comment]
@basvanbeek I can come up with a PR for this.

**Comment by jcchavezs** [comment]
Closed by #81 and #82
