### ISSUE TITLE
Improve failure messages for reporting

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#91]
Error log messages for reporting are meaningless https://github.com/openzipkin/zipkin-go/blob/master/reporter/http/http.go#L139 end up in 
```
2018/11/07 13:28:24 failed the request with status code 503
```
in logs which might not be useful. I was thinking on 
```
2018/11/07 13:28:24 failed the request to zipkin collector with status code 503
```
 Any suggestion @adriancole @basvanbeek ?

**Comment by adriancole** [comment]
if logging probably saying the endpoint is enough to clarify.

**Comment by jcchavezs** [comment]
@adriancole I actually see the value of printing both, sometimes you don't know what `172.x.x.12/v2/api/spans` is whereas sometimes problem is that people uses `/api/v2/spans` so including both might do the trick:

`2018/11/07 13:28:24 failed the request to zipkin collector (172.x.x.12/v2/api/spans) with status code 503`

**Comment by basvanbeek** [comment]
I think logging inside zipkin-go still needs a major overhaul. We shouldn't make assumptions on how stuff is being logged from within a library... that's an application concern.

Let's fix that and see what we need to do to improve reporting quality.
