### ISSUE TITLE
Possibility to not mark 4xx as failure in a server option

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#98]
There are some use cases where a 4xx server response does not mean an error at all. For example, an auth service would have a 403 as a response and marking it an error would be meaningless as there is nothing wrong here, it just the coupling inherited from the REST spec.

I would say this is more specific for server instrumentation as for the client a 403 is still an error (does not have to know the internals of the server returning the 403). I envision this as an option for the server middleware.

Ping @openzipkin/core

**Comment by llinder** [comment]
From experience it's hard to categorize whats best for 4xx codes.  Really it comes down to peculiarities of the services involved and what these mean.  For example we have cases where 403 may indicate a configuration issue and it's helpful to see as an error.  Other times on edge services 403 is mostly meaningless as it could just be an unauthenticated user.  Still at the same time a 403 might indicate a partner made a mistake and it's helpful to flag as an error.  404 also falls into the category of either meaningless and not helpful to flag as an error all the way to indicating a configuration or code bug and 404 as an error might be helpful.  Ideally speaking I would prefer that these things are configurable so services can make decisions or config can be tweaked to reduce noise.

**Comment by jcchavezs** [comment]
> I would offer to allow the error logic to be customizable as it is in
brave.

This is exactly what I aim to.

José Carlos Chávez


Den man. 10. des. 2018 kl. 18:56 skrev Lance Linder <
notifications@github.com>:

**Comment by jcchavezs** [comment]
@llinder agree, what people can do with REST is something complicated and comes down to what every service does. I would leave this as optional but of course provide an option for the user to decide.

@adriancole could you please point out the code where brave handles with the status code?
