### ISSUE TITLE
Add support for abandon a span

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin/zipkin-go#99]
Having the ability of abandoming a Span is convenient for those cases where an output makes the span meaningless.

APIs like [brave](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/Span.java#L174) and [zipkin-php](https://github.com/openzipkin/zipkin-php/tree/master/src/Zipkin) include such a thing.

Ping @adriancole @basvanbeek

**Comment by jcchavezs** [comment]
Closing this as it adds a lot of complications in context management.

**Comment by adriancole** [comment]
one opinion is that this should be limited to affect any pending data
directly referenced by the span (it can't affect scope in other words)
